### ISSUE TITLE
Issues while setting up AdmiralCloudConnector tool

### ISSUE THREAD

**Issue by Lehersun** [CPS-IT/admiral-cloud-connector#1]
I have typo3 application and wanted to install admiral-cloud-connector into. I have Debian 10, Postgres 11.
While installing I had several issues:
1. https://github.com/CPS-IT/admiral-cloud-connector/blob/f2b40d6b8e29ef549f0f5078cf7cd333e10f9f9a/Classes/Controller/Backend/BrowseLinksController.php#L246 contains php 7.4 syntax.
2. PHP Fatal error:  Declaration of TYPO3\CMS\Recordlist\LinkHandler\AbstractLinkHandler::initialize(TYPO3\CMS\Recordlist\Controller\AbstractLinkBrowserController $linkBrowser, $identifier, array $configuration) must be compatible with CPSIT\AdmiralCloudConnector\Backend\LinkHandlerInterface::initialize(CPSIT\AdmiralCloudConnector\Controller\Backend\AbstractLinkBrowserController $linkBrowser, $identifier, array $configuration) in /var/www/madeinbern/typo3conf/ext/admiral_cloud_connector/Classes/LinkHandler/PageLinkHandler.php on line 35
3. After manually create tables in database I've got this error: ```2022/10/16 21:54:47 [error] 603#603: *503 FastCGI sent in stderr: "PHP message: TYPO3 [WARNING] request="099a11d946b69" component="TYPO3.CMS.Core.TypoScript.Parser.TypoScriptParser": Illegal filepath "EXT:myexample/Configuration/TSconfig/Page/Linkvalidator.tsconfig". PHP message: TYPO3 [ERROR] request="099a11d946b69" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"userFunc = CPSIT\\AdmiralCloudConnector\\Utility\\PermissionUtility::userHasPermissionForAdmiralCloud()] && [typo3.branch == \"9.5\""}PHP message: TYPO3 [CRITICAL] request="099a11d946b69" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT "uid" FROM "tx_admiralcloudconnector_security_groups" WHERE ("tx_admiralcloudconnector_security_groups"."pid" = ?) AND (("tx_admiralcloudconnector_security_groups"."deleted" = 0) AND (("tx_admiralcloudconnector_security_groups"."t3ver_wsid" = 0) AND ("tx_admiralcloudconnector_security_groups"."t3ver_oid" = 0))) LIMIT 1' with params [0]:```. So I had to create two more columns t3ver_wsid, t3ver_oid.
4. ext_localconf.php shown error cause of using ```use``` in global scope.
5. After I fixed all above issues I've got another one when I'm going to Create new AC Security Group on root level 'm getting an error: ```SQLSTATE[42804]: Datatype mismatch: 7 ERROR: argument of AND must be type boolean, not type integer LINE 1: ...le", "be_groups"."hidden" FROM "be_groups" WHERE (1) AND ("b... ^. A SQL error occurred. This may indicate a schema mismatch between TCA and the database. Try running database compare in the Install Tool.``` Typo3 log gives me only this information: ```Mon, 17 Oct 2022 15:55:35 +0200 [ERROR] request="04a6656b39438" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"
userFunc = CPSIT\\AdmiralCloudConnector\\Utility\\PermissionUtility::userHasPermissionForAdmiralCloud()] && [typo3.branch == \"9.5\""}```

**Comment by kreidewe** [comment]
@Lehersun Thanks for your issue report.

We'll have a look on your open issue within the next 7 days.
Please help us to improve the component by providing your fixes, so we can merge them into the extension.

Best
Sebastian

**Comment by smeviuscps** [comment]
Hello,

I could reproduce this issue on AC Security Group creation with postgreSQL. Its now fixed in my newest commit.
The other issues you fixed by yourself I couldn't reproduce.

**Comment by Lehersun** [comment]
@smeviuscps, thank you for the fix. I've tried one more time to reinstall this extension. Now when I'm going to Create new AC Security Group I'm getting next errors:
- ```[ERROR] request="cc3ca1d3185cb" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"userFunc = CPSIT\\AdmiralCloudConnector\\Utility\\PermissionUtility::userHasPermissionForAdmiralCloud()] && [typo3.branch == \"9.5\""}```
- ```request="cc3ca1d3185cb" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1559128872210: Missing Admiral Cloud file storage | CPSIT\AdmiralCloudConnector\Exception\InvalidArgumentException thrown in file /var/www/madeinbern/typo3conf/ext/admiral_cloud_connector/Classes/Traits/AdmiralCloudStorage.php in line 52. Requested URL: https://mysite.local/typo3/index.php?route=%2Fmodule%2Fweb%2Flayout&token=--AnonymizedToken--&id=1& - {"TYPO3_MODE":"BE","exception":null}```

Do you have any ideas what could be a reason?

**Comment by smeviuscps** [comment]
Hello, 
thanks for your pull Request. I have added it now to master.
For the other two issues I made a change to the tsconfig path for the linkhandler and I removed the permission check.
You have the error "missing admiral cloud file storage". You need to create a Admrialcloud storage like described here: https://docs.typo3.org/p/cpsit/admiral-cloud-connector/1.0/en-us/Installation/Index.html

**Comment by meisterkaiser** [comment]
@Lehersun 
Hi - did the last release fix your problems?
Can this issue be closed?

**Comment by Lehersun** [comment]
@meisterkaiser, thank you for answers. Issue was fixed
